# Copyright (c) 2022 Sapphire's Suite. All Rights Reserved.

name: MacOS

# Trigger the action.
on:
  push:
    branches:
      - main
      - master
      - dev
      - dev_*
      - '!dev_unix'
      - '!dev_win'


# Settings common to all jobs.
defaults:
  run:
    shell: bash


# Variables common to all jobs.
env:
  CMAKE_V: '3.17.0'
  CMAKE_OPTIONS: '-DSA_CI=1 -DSA_LOGGER_BUILD_TESTS_OPT=ON'


# Job matrix
jobs:

  ctests_macos:
    name: ${{ matrix.config }} ${{ matrix.gen }} ${{ matrix.compiler }} ${{ matrix.compiler_v }}

    # Setup environment.
    runs-on: macos-latest

    strategy:

      # Don't cancel jobs on failure.
      fail-fast: false

      matrix:

        config:
          - Debug
          - Release

        gen:
          - Xcode
          - Ninja

        include:
          - gen: Xcode
            compiler_v: 11.7
          - gen: Xcode
            compiler_v: 12.5
          - gen: Xcode
            compiler_v: latest-stable

          - gen: Ninja
            compiler: GNU
            compiler_v: 11


    # Steps execution.
    steps:

        - name: "[Action] Checkout repository"
          uses: actions/checkout@v2
          with:
            submodules: recursive


        # Install CMake.
        - name: "[Action] Install CMake"
          uses: jwlawson/actions-setup-cmake@v1.8
          with:
            cmake-version: ${{ env.CMAKE_V }}


#{ Generators

        # Install Ninja.
        - name: "[Action] Install Ninja 1/2"
          if: ${{ matrix.gen == 'Ninja' }}
          uses: seanmiddleditch/gha-setup-ninja@master

        # Set env variables.
        - name: "[Command] Install Ninja 2/2"
          if: ${{ matrix.gen == 'Ninja' }}
          run: echo "GEN=Ninja" >> $GITHUB_ENV


        # Install Xcode.
        - name: "[Action] Install Xcode 1/2"
          if: ${{ matrix.gen == 'Xcode' }}
          uses: maxim-lobanov/setup-xcode@v1
          with:
            xcode-version: ${{ matrix.compiler_v }}

        # Set env variables.
        - name: "[Command] Install Xcode 2/2"
          if: ${{ matrix.gen == 'Xcode' }}
          run: echo "GEN=Xcode" >> $GITHUB_ENV
#}


#{ Compilers

        # Install GCC.
        - name: "[Package] Install GCC"
          if: ${{ matrix.compiler == 'GNU' }}
          run: |
              brew install gcc@${{ matrix.compiler_v }}
              echo "CC=gcc-${{ matrix.compiler_v }}" >> $GITHUB_ENV
              echo "CXX=g++-${{ matrix.compiler_v }}" >> $GITHUB_ENV

#}


#{ Build & Test

        # Deploy & Build & Test
        - name: Generate Project
          run: cmake -B Build/${{ matrix.gen }}/${{ matrix.config }} -DCMAKE_BUILD_TYPE=${{ matrix.config }} ${{ env.CMAKE_OPTIONS }} -G ${GEN}

        - name: Build Project
          run: cmake --build Build/${{ matrix.gen }}/${{ matrix.config }} --config ${{ matrix.config }} --verbose

        - name: Run CTests
          run: cd Build/${{ matrix.gen }}/${{ matrix.config }} && ctest -C ${{ matrix.config }} -V

#}
